import "../globals.css";
import Link from "next/link";
import { getPages } from "@/sanitty/sanity-utils";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "My Awesome Site",
  description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html
      lang="en"
      className="max-w-80 mx-auto py-4 bg-[url('../public/bg3.jpg')] bg-no-repeat bg-cover bg-opacity-40 bg-center"
    >
      <body className="max-w-80 mx-auto">
        <Navbar />
        <main className="py-10">{children}</main>
      </body>
    </html>
  );
}

